# Generated by Django 5.1.15 on 2026-01-26 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_wallet_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=20)),
                ('btc_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('eth_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('sol_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('bnb_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('ada_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
