# Generated by Django 5.1.15 on 2026-01-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('STOCK', 'Stock'), ('FOREX', 'Forex')], max_length=20)),
                ('is_tradable', models.BooleanField(default=True)),
            ],
        ),
    ]
